#!/bin/bash

# This script should be used instead of Concourse "fly" cli in order to deploy
# the pipeline. It simply calls "erb" to render the final pipeline definition.
# It delegated all other options to the real "fly".

exec fly ${@} --config <(erb pipeline.yaml.erb)
