{{- if .Values.features.routing_api.enabled }}

# Add quarks properties for routing-api.
- type: replace
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/quarks?
  value:
    envs:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    ports:
    - name: routing-api
      protocol: TCP
      internal: 3000
    activePassiveProbes:
      routing-api-routing-api:
        exec:
          command:
          - bash
          - -ce
          - "head -c0 </dev/tcp/${HOSTNAME}/3000 "
# Set the alias routing-api.service.cf.internal instance group to routing-api.
- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=routing-api.service.cf.internal/targets/0/instance_group
  value: routing-api

{{- range $bytes := .Files.Glob "assets/operations/pre_render_scripts/routing-api_*" }}
{{ $bytes | toString }}
{{- end }}

{{- else }}
# Disable routing-api.
- type: remove
  path: /instance_groups/name=api/jobs/name=routing-api

- type: remove
  path: /instance_groups/name=database?/jobs/name=pxc-mysql/properties/seeded_databases/name=routing-api

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/routing_api/enabled
  value: false

- type: remove
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=routing-api.service.cf.internal

- type: remove
  path: /variables/name=routing_api_tls

- type: remove
  path: /variables/name=routing_api_tls_client
{{- end }}
