#!/usr/bin/env bash

set -o errexit -o nounset

# create the cluster
kind create cluster --name scf

# use the kube config file generated by kind
export KUBECONFIG="$(kind get kubeconfig-path --name="scf")"

# setup tiller
kubectl create -f ~/tools/kube/tiller.yaml
helm init --service-account tiller

# create a storage class
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false", "storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true", "storageclass.beta.kubernetes.io/is-default-class":"true"}}}'
